Url =https://adactinhotelapp.com/index.php

###Valid username and password ###

browser = edge
validusername=Sangee986
validpassword=sangee123

###InValid username and password ###

browser1=headless-chrome
invalidusername=Sangee896
InvalidTestCaseName=InvalidUsernameAndValidPassword
InvalidExpectedMessage=Login was unsuccessful.